language: python
dist: xenial
env:
    global:
        - SKIP_GENERATE_AUTHORS=1
        - SKIP_WRITE_GIT_CHANGELOG=1
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install -U pip
    - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install pathlib2; fi
    - pip install .[test]
script:
    - py.test -v tests
deploy:
    provider: pypi
    user: jbarnoud
    password:
        secure: Fy15pKRBA2eZw0gRAduTWoqK0lMkFPVCtqmhEMVXKfRl+R94hIMsGu4QyO4EeKeeVY3icDOWCG8dyGq6DPgmnQXfHyo7qYD1VtNKS8+UxhgVVQGLwoMW+ch+sh3C9RT84aQhP3i81bt2OuYx9mLJA8r6ajLBOmuC5/k8F6owqYCH2kDl7Etb0yCOrW6dBQi/+tQs7JEn61YRHu1Mc/MXQ+Hl5Ywuw3i8Urc4AeLgoeTVFuN4tHa6O0K7VP727PzfMEk7gkX/bTtBdxLEPVrC6z/71AtvMH+vljEmI3oejJqF/E8ZrxOVa9gWORXH+cZiVOBvj2LbO9MxGeayEoPRhCivlBEqEnD8VblRvVEHMUfizhsEvz3DSav1NPU32asemqfqHlv5B45hpAGyeQsjWAavm++kbOIMas3BwnHOywIYms+b2Ns4A9EWBFzHYSdH6hnXrfrkE9Slw8SyGGDoBw6NHCYGYDJj1rBmnXNt95wLb0hNJG2GBKJkPDDckWJu2dNIAiQiWc8hNXdrXmsWg2YY2TWfAfelBqRk99LK1lnf8ZzxvXhH13/6wXbADFgkXd/+HrRd98dX8ih59yQUK9qbFfp7gMkTg92E+qh6LzfmnOdyrmy15BPqeJhMfjf2BeTBQR2VTUoWJbwrKabO10IFSZ8jqQM1q+VSPHpLwfA=
    distributions: sdist bdist_wheel
    skip_existing: true
